scraper:
  image: scraper
  links:
   - mongo
   - rabbitmq
mongo:
  image: mongo
rabbitmq:
  image: rabbitmq
phox:
  image: phox_pipe
  links:
   - rabbitmq
   - hypnos
hypnos:
  image: caerusassociates/hypnos
  links:
   - ccnlp
   - petrarch
  ports:
   - "5002:5002"
ccnlp:
  image: caerusassociates/ccnlp:1.0.0
petrarch:
  image: petrarch
